# Generated by Django 3.2.9 on 2021-11-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('level_graph', models.CharField(max_length=100)),
                ('run_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaderbord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.runs')),
            ],
        ),
    ]
