# Generated by Django 3.2.9 on 2021-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='seed',
            field=models.CharField(max_length=30),
        ),
    ]
