# Generated by Django 3.2.9 on 2021-11-11 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_alter_runs_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='run_date',
            field=models.DateField(default=datetime.date(2021, 11, 11)),
        ),
    ]
