# Generated by Django 3.2.9 on 2021-11-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_runs_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runs',
            name='level_graph',
        ),
    ]
