# Generated by Django 3.2.9 on 2021-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_remove_runs_level_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='run_date',
            field=models.DateField(default='django.utils.timezone.now'),
        ),
    ]
