# Generated by Django 3.2.9 on 2021-11-11 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_alter_runs_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='run_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 15, 3, 21, 154714, tzinfo=utc)),
        ),
    ]
